/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WritingRouteImport } from './routes/writing'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as AucklandRouteImport } from './routes/auckland'
import { Route as AdventuresRouteImport } from './routes/adventures'
import { Route as IndexRouteImport } from './routes/index'

const WritingRoute = WritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AucklandRoute = AucklandRouteImport.update({
  id: '/auckland',
  path: '/auckland',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventuresRoute = AdventuresRouteImport.update({
  id: '/adventures',
  path: '/adventures',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adventures': typeof AdventuresRoute
  '/auckland': typeof AucklandRoute
  '/favorites': typeof FavoritesRoute
  '/projects': typeof ProjectsRoute
  '/writing': typeof WritingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adventures': typeof AdventuresRoute
  '/auckland': typeof AucklandRoute
  '/favorites': typeof FavoritesRoute
  '/projects': typeof ProjectsRoute
  '/writing': typeof WritingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adventures': typeof AdventuresRoute
  '/auckland': typeof AucklandRoute
  '/favorites': typeof FavoritesRoute
  '/projects': typeof ProjectsRoute
  '/writing': typeof WritingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adventures'
    | '/auckland'
    | '/favorites'
    | '/projects'
    | '/writing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adventures'
    | '/auckland'
    | '/favorites'
    | '/projects'
    | '/writing'
  id:
    | '__root__'
    | '/'
    | '/adventures'
    | '/auckland'
    | '/favorites'
    | '/projects'
    | '/writing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdventuresRoute: typeof AdventuresRoute
  AucklandRoute: typeof AucklandRoute
  FavoritesRoute: typeof FavoritesRoute
  ProjectsRoute: typeof ProjectsRoute
  WritingRoute: typeof WritingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writing': {
      id: '/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auckland': {
      id: '/auckland'
      path: '/auckland'
      fullPath: '/auckland'
      preLoaderRoute: typeof AucklandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures': {
      id: '/adventures'
      path: '/adventures'
      fullPath: '/adventures'
      preLoaderRoute: typeof AdventuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdventuresRoute: AdventuresRoute,
  AucklandRoute: AucklandRoute,
  FavoritesRoute: FavoritesRoute,
  ProjectsRoute: ProjectsRoute,
  WritingRoute: WritingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
